/**
 * LINBO Plugin - Simple Drivers Service
 * Folder-based driver matching using match.conf (INI-style).
 *
 * Each hardware model gets a folder in /drivers/ with a match.conf file
 * containing [match] section with vendor + product keys.
 */

const fs = require('fs').promises;
const path = require('path');
const os = require('os');
const { DRIVERS_BASE, sanitizeName, sanitizeRelativePath, resolveAndValidate, MAX_ZIP_ENTRIES, MAX_ZIP_SIZE } = require('../lib/driver-path');
const { IMAGES_DIR } = require('../lib/image-path');
const { listDirRecursive, countFiles, getDirSize, removeSymlinks } = require('../lib/driver-fs');
const sshService = require('./ssh.service');
const ws = require('../lib/websocket');

/**
 * Walk a directory recursively and verify no file resolves outside the root.
 * Throws with statusCode 400 on path traversal detection.
 */
async function validateExtractedPaths(rootDir) {
  const resolvedRoot = path.resolve(rootDir);
  const entries = await listDirRecursive(rootDir);
  for (const entry of entries) {
    const resolved = path.resolve(rootDir, entry);
    if (!resolved.startsWith(resolvedRoot + path.sep) && resolved !== resolvedRoot) {
      throw Object.assign(
        new Error(`Path traversal detected in extracted file: ${entry}`),
        { statusCode: 400 }
      );
    }
  }
}

/**
 * Move all contents from srcDir into destDir (merging).
 */
async function moveContents(srcDir, destDir) {
  await fs.mkdir(destDir, { recursive: true });
  const entries = await fs.readdir(srcDir, { withFileTypes: true });
  for (const entry of entries) {
    const src = path.join(srcDir, entry.name);
    const dest = path.join(destDir, entry.name);
    if (entry.isDirectory()) {
      await moveContents(src, dest);
    } else {
      await fs.rename(src, dest).catch(async () => {
        // rename fails across filesystems — fallback to copy+delete
        await fs.copyFile(src, dest);
        await fs.unlink(src);
      });
    }
  }
}

// =============================================================================
// Match.conf Parsing
// =============================================================================

/**
 * Parse an INI-style match.conf content.
 * Looks for [match] section, extracts vendor and product lines.
 * @param {string} content - Raw match.conf content
 * @returns {{ vendor: string, products: string[] }}
 */
function parseMatchConf(content) {
  const lines = content.split('\n');
  let inMatch = false;
  let vendor = '';
  const products = [];

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip comments and empty lines
    if (trimmed === '' || trimmed.startsWith('#')) continue;

    // Section detection
    if (trimmed.startsWith('[')) {
      inMatch = trimmed.toLowerCase() === '[match]';
      continue;
    }

    if (!inMatch) continue;

    // Parse key = value
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;

    const key = trimmed.substring(0, eqIdx).trim().toLowerCase();
    const value = trimmed.substring(eqIdx + 1).trim();

    if (key === 'vendor') {
      vendor = value;
    } else if (key === 'product') {
      products.push(value);
    }
  }

  return { vendor, products };
}

// =============================================================================
// Profile Operations
// =============================================================================

/**
 * Create a driver profile by reading DMI from a LINBO client via SSH.
 * @param {string} hostIp - IP of the LINBO client to read DMI from
 * @returns {Promise<{ created: boolean, folder: string, vendor: string, product: string }>}
 */
async function createProfile(hostIp) {
  // 1. SSH to host and read DMI data
  const result = await sshService.executeWithTimeout(
    hostIp,
    'cat /sys/class/dmi/id/sys_vendor && echo "---DMI_SEP---" && cat /sys/class/dmi/id/product_name',
    10000
  );

  const parts = result.stdout.split('---DMI_SEP---');
  const vendor = (parts[0] || '').trim();
  const product = (parts[1] || '').trim();

  if (!vendor || !product) {
    const err = new Error('Could not read DMI vendor/product from host');
    err.statusCode = 502;
    throw err;
  }

  // 2. Derive folder name
  const rawName = `${vendor}_${product}`
    .replace(/\s+/g, '_')
    .replace(/[^a-zA-Z0-9._-]/g, '')
    .substring(0, 80);

  const folderName = sanitizeName(rawName);

  // 3. Resolve and validate path
  const folderPath = await resolveAndValidate(folderName);
  const matchConfPath = path.join(folderPath, 'match.conf');

  // 4. Check if already exists
  try {
    await fs.access(matchConfPath);
    // match.conf exists -- idempotent return
    return { created: false, folder: folderName, vendor, product };
  } catch {
    // Does not exist, create it
  }

  // 5. Create directory
  await fs.mkdir(folderPath, { recursive: true });

  // 6. Write match.conf
  const confContent = [
    '# Auto-generated by LINBO Plugin API',
    `# Hardware: ${vendor} / ${product}`,
    '[match]',
    `vendor = ${vendor}`,
    `product = ${product}`,
    '',
  ].join('\n');

  await fs.writeFile(matchConfPath, confContent, 'utf-8');

  // 7. Broadcast WS event
  ws.broadcast('drivers.profile_created', { folder: folderName, vendor, product });

  return { created: true, folder: folderName, vendor, product };
}

/**
 * List all simple driver profiles (folders with match.conf).
 * Skips legacy folders (those with driver-map.json but no match.conf).
 * @returns {Promise<Array<{ folder: string, vendor: string, product: string, hasDrivers: boolean, fileCount: number, totalSize: number }>>}
 */
async function listProfiles() {
  let entries;
  try {
    entries = await fs.readdir(DRIVERS_BASE, { withFileTypes: true });
  } catch {
    // Base dir does not exist yet
    return [];
  }

  const profiles = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const matchConfPath = path.join(DRIVERS_BASE, entry.name, 'match.conf');
    try {
      const content = await fs.readFile(matchConfPath, 'utf-8');
      const parsed = parseMatchConf(content);

      // Check if dir has files beyond match.conf
      const dirPath = path.join(DRIVERS_BASE, entry.name);
      const files = await fs.readdir(dirPath);
      const hasDrivers = files.some(f => f !== 'match.conf');

      // Count files and total size for the profile
      const fileCount = await countFiles(dirPath);
      const totalSize = await getDirSize(dirPath);

      // Read image assignment
      const image = await readImageConf(entry.name);

      profiles.push({
        folder: entry.name,
        vendor: parsed.vendor,
        product: parsed.products[0] || '',
        hasDrivers,
        fileCount,
        totalSize,
        image,
      });
    } catch {
      // No match.conf -- not a simple driver profile, skip
      continue;
    }
  }

  return profiles;
}

/**
 * Get match.conf data for a specific profile folder.
 * @param {string} folderName - Name of the profile folder
 * @returns {Promise<{ folder: string, vendor: string, products: string[], raw: string }>}
 */
async function getMatchConf(folderName) {
  const safeName = sanitizeName(folderName);
  const matchConfPath = path.join(DRIVERS_BASE, safeName, 'match.conf');

  let content;
  try {
    content = await fs.readFile(matchConfPath, 'utf-8');
  } catch {
    const err = new Error(`match.conf not found in profile "${safeName}"`);
    err.statusCode = 404;
    throw err;
  }

  const parsed = parseMatchConf(content);
  return { folder: safeName, vendor: parsed.vendor, products: parsed.products, raw: content };
}

// =============================================================================
// Image Assignment
// =============================================================================

/**
 * Read image.conf from a profile folder.
 * Returns the image name string or null if file does not exist.
 * @param {string} folderName - Name of the profile folder
 * @returns {Promise<string|null>}
 */
async function readImageConf(folderName) {
  const imageConfPath = path.join(DRIVERS_BASE, folderName, 'image.conf');
  let content;
  try {
    content = await fs.readFile(imageConfPath, 'utf-8');
  } catch {
    return null;
  }

  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (trimmed === '' || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.substring(0, eqIdx).trim().toLowerCase();
    const value = trimmed.substring(eqIdx + 1).trim();
    if (key === 'image' && value) return value;
  }

  return null;
}

/**
 * List available images (subdirectories of IMAGES_DIR containing .qcow2 files).
 * @returns {Promise<Array<{name: string, filename: string}>>}
 */
async function listAvailableImages() {
  let entries;
  try {
    entries = await fs.readdir(IMAGES_DIR, { withFileTypes: true });
  } catch {
    return [];
  }

  const images = [];
  const skipDirs = new Set(['tmp', 'backups']);

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (skipDirs.has(entry.name)) continue;

    const dirPath = path.join(IMAGES_DIR, entry.name);
    let files;
    try {
      files = await fs.readdir(dirPath);
    } catch {
      continue;
    }

    const qcow2 = files.find(f => f.endsWith('.qcow2'));
    if (qcow2) {
      images.push({ name: entry.name, filename: qcow2 });
    }
  }

  return images;
}

/**
 * Assign a profile to an image. Writes image.conf and regenerates postsync.
 * @param {string} folderName - Profile folder name
 * @param {string} imageName - Image name (directory name in IMAGES_DIR)
 * @returns {Promise<{folder: string, image: string}>}
 */
async function setProfileImage(folderName, imageName) {
  const safeName = sanitizeName(folderName);

  // Validate profile exists (has match.conf)
  const matchConfPath = path.join(DRIVERS_BASE, safeName, 'match.conf');
  try {
    await fs.access(matchConfPath);
  } catch {
    const err = new Error(`Profile not found: ${safeName}`);
    err.statusCode = 404;
    throw err;
  }

  // Validate image name format
  if (!imageName || typeof imageName !== 'string') {
    const err = new Error('Image name must not be empty');
    err.statusCode = 400;
    throw err;
  }
  if (!/^[a-zA-Z0-9][a-zA-Z0-9._-]*$/.test(imageName)) {
    const err = new Error('Image name must start with alphanumeric and contain only [a-zA-Z0-9._-]');
    err.statusCode = 400;
    throw err;
  }

  // Write image.conf
  const imageConfPath = path.join(DRIVERS_BASE, safeName, 'image.conf');
  const confContent = [
    '# Image assignment for driver profile',
    `image = ${imageName}`,
    '',
  ].join('\n');
  await fs.writeFile(imageConfPath, confContent, 'utf-8');

  // Regenerate postsync for this image
  await regeneratePostsync(imageName);

  ws.broadcast('drivers.image_assigned', { folder: safeName, image: imageName });

  return { folder: safeName, image: imageName };
}

/**
 * Remove the image assignment for a profile. Deletes image.conf and regenerates postsync.
 * @param {string} folderName - Profile folder name
 * @returns {Promise<{folder: string, image: null}>}
 */
async function removeProfileImage(folderName) {
  const safeName = sanitizeName(folderName);
  const imageConfPath = path.join(DRIVERS_BASE, safeName, 'image.conf');

  // Read current image name before deleting
  const currentImage = await readImageConf(safeName);

  // Delete image.conf (idempotent)
  try {
    await fs.unlink(imageConfPath);
  } catch {
    // File does not exist — return silently
    return { folder: safeName, image: null };
  }

  // Regenerate postsync for the previously assigned image (other profiles may still reference it)
  if (currentImage) {
    await regeneratePostsync(currentImage);
  }

  ws.broadcast('drivers.image_removed', { folder: safeName });

  return { folder: safeName, image: null };
}

/**
 * Regenerate the postsync script for a given image.
 * Scans ALL profile folders to find which ones reference this image.
 * If none reference it, deletes the postsync. Otherwise generates a self-contained script.
 * @param {string} imageName - Image directory name
 * @returns {Promise<void>}
 */
async function regeneratePostsync(imageName) {
  // Find all profiles that reference this image
  let entries;
  try {
    entries = await fs.readdir(DRIVERS_BASE, { withFileTypes: true });
  } catch {
    entries = [];
  }

  const referencingProfiles = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const img = await readImageConf(entry.name);
    if (img === imageName) {
      referencingProfiles.push(entry.name);
    }
  }

  const postsyncPath = path.join(IMAGES_DIR, imageName, imageName + '.treiberpostsync');

  if (referencingProfiles.length === 0) {
    // No profiles reference this image — delete postsync if it exists
    try {
      await fs.unlink(postsyncPath);
    } catch {
      // File does not exist — nothing to do
    }
    ws.broadcast('drivers.treiberpostsync_updated', { image: imageName, profiles: 0 });
    return;
  }

  // Ensure image directory exists
  const imageDir = path.join(IMAGES_DIR, imageName);
  await fs.mkdir(imageDir, { recursive: true });

  // Generate self-contained postsync script with inline match logic
  const script = `#!/bin/sh
# =============================================================================
# Auto-generated postsync script for image: ${imageName}
# Generated by LINBO Plugin API — DO NOT EDIT MANUALLY
# Profiles: ${referencingProfiles.join(', ')}
# =============================================================================

LOG="/tmp/linbo-drivers-postsync.log"
echo "=== LINBO Driver Postsync for ${imageName} $(date) ===" > "$LOG"

# Sync all driver profiles from server
echo "Syncing driver profiles from server..." | tee -a "$LOG"
rsync -a "$LINBOSERVER::drivers/" /cache/linbo-drivers/ 2>&1 | tee -a "$LOG"

# Read client DMI
SYS_VENDOR=$(cat /sys/class/dmi/id/sys_vendor 2>/dev/null | tr -d '\\n\\r' | sed 's/[[:space:]]*$//')
PRODUCT_NAME=$(cat /sys/class/dmi/id/product_name 2>/dev/null | tr -d '\\n\\r' | sed 's/[[:space:]]*$//')
echo "DMI: vendor='$SYS_VENDOR' product='$PRODUCT_NAME'" | tee -a "$LOG"

TARGET="/mnt/Drivers/LINBO"
MATCHED_FOLDERS=""

# Iterate all driver profile folders
for PROFILE_DIR in /cache/linbo-drivers/*/; do
    [ -d "$PROFILE_DIR" ] || continue
    CONF="$PROFILE_DIR/match.conf"
    [ -f "$CONF" ] || continue

    FOLDER=$(basename "$PROFILE_DIR")

    # Parse match.conf — extract vendor and product lines
    CONF_VENDOR=""
    CONF_PRODUCTS=""
    IN_MATCH=0
    while IFS= read -r line; do
        case "$line" in
            \\#*|"") continue ;;
            \\[match\\]*) IN_MATCH=1; continue ;;
            \\[*) IN_MATCH=0; continue ;;
        esac
        [ "$IN_MATCH" = "0" ] && continue

        key=$(echo "$line" | sed 's/[[:space:]]*=.*//' | tr -d ' ')
        value=$(echo "$line" | sed 's/[^=]*=[[:space:]]*//')

        case "$key" in
            vendor) CONF_VENDOR="$value" ;;
            product) CONF_PRODUCTS="$CONF_PRODUCTS|$value" ;;
        esac
    done < "$CONF"

    # Wildcard match
    if [ -z "$CONF_VENDOR" ] || [ "$CONF_VENDOR" = "*" ]; then
        echo "  $FOLDER: default/wildcard profile, matched" | tee -a "$LOG"
        MATCHED_FOLDERS="$MATCHED_FOLDERS $FOLDER"
        continue
    fi

    # Vendor must match exactly
    if [ "$CONF_VENDOR" != "$SYS_VENDOR" ]; then
        continue
    fi

    # Product substring match
    if [ -z "$CONF_PRODUCTS" ] || [ "$CONF_PRODUCTS" = "|*" ]; then
        echo "  $FOLDER: vendor matched, wildcard product" | tee -a "$LOG"
        MATCHED_FOLDERS="$MATCHED_FOLDERS $FOLDER"
        continue
    fi

    OLD_IFS="$IFS"
    IFS="|"
    for pat in $CONF_PRODUCTS; do
        [ -z "$pat" ] && continue
        case "$PRODUCT_NAME" in
            *"$pat"*)
                echo "  $FOLDER: matched (product contains '$pat')" | tee -a "$LOG"
                MATCHED_FOLDERS="$MATCHED_FOLDERS $FOLDER"
                break
                ;;
        esac
    done
    IFS="$OLD_IFS"
done

echo "Matched folders: $MATCHED_FOLDERS" | tee -a "$LOG"

# Copy matched driver folders to Windows target
for FOLDER in $MATCHED_FOLDERS; do
    SRC="/cache/linbo-drivers/$FOLDER"
    if [ -d "$SRC" ]; then
        FILE_COUNT=$(find "$SRC" -type f ! -name "match.conf" ! -name "image.conf" 2>/dev/null | wc -l)
        if [ "$FILE_COUNT" -gt 0 ]; then
            echo "  Copying drivers from: $FOLDER ($FILE_COUNT files)" | tee -a "$LOG"
            mkdir -p "$TARGET/$FOLDER"
            find "$SRC" -type f ! -name "match.conf" ! -name "image.conf" -exec cp -a {} "$TARGET/$FOLDER/" \\; 2>/dev/null
        else
            echo "  $FOLDER: no driver files, skipping copy" | tee -a "$LOG"
        fi
    fi
done

# pnputil setup if INF files were copied
INF_COUNT=$(find "$TARGET" -iname '*.inf' 2>/dev/null | wc -l)
if [ "$INF_COUNT" -gt 0 ]; then
    printf '@echo off\\r\\n' > "$TARGET/pnputil-install.cmd"
    printf 'pnputil /add-driver C:\\\\Drivers\\\\LINBO\\\\*.inf /subdirs /install\\r\\n' >> "$TARGET/pnputil-install.cmd"
    printf 'del "%%~f0"\\r\\n' >> "$TARGET/pnputil-install.cmd"
    printf 'exit /b 0\\r\\n' >> "$TARGET/pnputil-install.cmd"

    cat > /tmp/linbo-driver-install.reg << 'REG'
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce]
"LinboDriverInstall"="C:\\\\Drivers\\\\LINBO\\\\pnputil-install.cmd"
REG
    linbo_patch_registry /tmp/linbo-driver-install.reg 2>&1 | tee -a "$LOG"
    rm -f /tmp/linbo-driver-install.reg
    echo "Driver auto-install: $INF_COUNT INF files, RunOnce set" | tee -a "$LOG"
else
    echo "No INF files found — skipping pnputil setup" | tee -a "$LOG"
fi

cp "$LOG" "/cache/linbo-drivers-postsync.log" 2>/dev/null
`;

  await fs.writeFile(postsyncPath, script, { mode: 0o755 });

  ws.broadcast('drivers.treiberpostsync_updated', { image: imageName, profiles: referencingProfiles.length });
}

// =============================================================================
// File Management
// =============================================================================

/**
 * List all files in a driver profile folder.
 * Excludes match.conf from the listing (it's metadata, not a driver file).
 * @param {string} folderName - Name of the profile folder
 * @returns {Promise<Array<{name: string, path: string, size: number, isDirectory: boolean}>>}
 */
async function listFiles(folderName) {
  const safeName = sanitizeName(folderName);
  const folderPath = await resolveAndValidate(safeName);

  let allFiles;
  try {
    allFiles = await listDirRecursive(folderPath, '');
  } catch (err) {
    if (err.code === 'ENOENT') {
      const error = new Error(`Profile not found: ${safeName}`);
      error.statusCode = 404;
      throw error;
    }
    throw err;
  }

  // Exclude match.conf from the listing
  return allFiles.filter(f => f.path !== 'match.conf');
}

/**
 * Upload a file into a driver profile folder.
 * @param {string} folderName - Name of the profile folder
 * @param {string} relPath - Relative path within the folder
 * @param {Buffer} buffer - File content
 * @returns {Promise<{path: string, size: number}>}
 */
async function uploadFile(folderName, relPath, buffer) {
  const safeName = sanitizeName(folderName);
  const safeRelPath = sanitizeRelativePath(relPath);
  const filePath = await resolveAndValidate(safeName, safeRelPath);

  // Ensure parent directory exists
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, buffer, { mode: 0o644 });

  const stat = await fs.stat(filePath);

  ws.broadcast('drivers.file_uploaded', { folder: safeName, path: safeRelPath, size: stat.size });

  return { path: safeRelPath, size: stat.size };
}

/**
 * Delete a file from a driver profile folder.
 * @param {string} folderName - Name of the profile folder
 * @param {string} relPath - Relative path of the file to delete
 * @returns {Promise<{deleted: string}>}
 */
async function deleteFile(folderName, relPath) {
  const safeName = sanitizeName(folderName);
  const safeRelPath = sanitizeRelativePath(relPath);
  const filePath = await resolveAndValidate(safeName, safeRelPath);

  try {
    await fs.unlink(filePath);
  } catch (unlinkErr) {
    if (unlinkErr.code === 'ENOENT') {
      const err = new Error(`File not found: ${safeRelPath}`);
      err.statusCode = 404;
      throw err;
    }
    throw unlinkErr;
  }

  ws.broadcast('drivers.file_deleted', { folder: safeName, path: safeRelPath });

  return { deleted: safeRelPath };
}

/**
 * Delete an entire driver profile folder.
 * @param {string} folderName - Name of the profile folder
 * @returns {Promise<{deleted: string}>}
 */
async function deleteProfile(folderName) {
  const safeName = sanitizeName(folderName);
  const dirPath = await resolveAndValidate(safeName);

  // Use readdir instead of access to avoid TOCTOU race
  try {
    await fs.readdir(dirPath);
  } catch (readErr) {
    if (readErr.code === 'ENOENT') {
      const err = new Error(`Profile not found: ${safeName}`);
      err.statusCode = 404;
      throw err;
    }
    throw readErr;
  }

  await fs.rm(dirPath, { recursive: true, force: true });

  ws.broadcast('drivers.profile_deleted', { folder: safeName });

  return { deleted: safeName };
}

/**
 * Update match.conf content for a driver profile.
 * @param {string} folderName - Name of the profile folder
 * @param {string} content - New match.conf content
 * @returns {Promise<{folder: string, vendor: string, products: string[]}>}
 */
async function updateMatchConf(folderName, content) {
  const safeName = sanitizeName(folderName);

  if (typeof content !== 'string') {
    const err = new Error('Content must be a string');
    err.statusCode = 400;
    throw err;
  }

  if (content.length > 10 * 1024) {
    const err = new Error('Content exceeds maximum size (10KB)');
    err.statusCode = 400;
    throw err;
  }

  // Validate match values before writing (prevents shell injection in postsync scripts)
  const { validateMatchValue } = require('../lib/driver-shell');
  const parsed = parseMatchConf(content);

  const vendorErr = validateMatchValue(parsed.vendor);
  if (vendorErr) {
    const err = new Error(`Invalid vendor in match.conf: ${vendorErr}`);
    err.statusCode = 400;
    throw err;
  }
  for (const product of parsed.products) {
    const productErr = validateMatchValue(product);
    if (productErr) {
      const err = new Error(`Invalid product in match.conf: ${productErr}`);
      err.statusCode = 400;
      throw err;
    }
  }

  const matchConfPath = await resolveAndValidate(safeName, 'match.conf');

  // Atomic write with random suffix (PID-reuse safe) + cleanup on failure
  const suffix = Date.now() + '-' + Math.random().toString(36).slice(2);
  const tmp = matchConfPath + '.tmp.' + suffix;
  try {
    await fs.writeFile(tmp, content, { mode: 0o644 });
    await fs.rename(tmp, matchConfPath);
  } catch (writeErr) {
    await fs.unlink(tmp).catch(() => {});
    throw writeErr;
  }

  ws.broadcast('drivers.match_conf_updated', { folder: safeName, vendor: parsed.vendor, products: parsed.products });

  return { folder: safeName, vendor: parsed.vendor, products: parsed.products };
}

/**
 * Extract an archive (ZIP, EXE, 7z) into a driver profile folder.
 * @param {string} folderName - Name of the profile folder
 * @param {string} archivePath - Path to the uploaded archive on disk
 * @param {string} originalName - Original filename (for format detection)
 * @returns {Promise<{entryCount: number, totalUncompressed: number}>}
 */
async function extractArchive(folderName, archivePath, originalName) {
  const safeName = sanitizeName(folderName);
  const profileDir = await resolveAndValidate(safeName);

  // Verify profile directory exists
  try {
    await fs.access(profileDir);
  } catch {
    const err = new Error(`Profile not found: ${safeName}`);
    err.statusCode = 404;
    throw err;
  }

  // Concurrency lock — prevent parallel extractions to same profile
  const lockFile = path.join(profileDir, '.extracting');
  try {
    await fs.writeFile(lockFile, `${process.pid}\n${new Date().toISOString()}`, { flag: 'wx' });
  } catch (lockErr) {
    if (lockErr.code === 'EEXIST') {
      const err = new Error(`Extraction already in progress for profile: ${safeName}`);
      err.statusCode = 409;
      throw err;
    }
    throw lockErr;
  }

  try {
    return await _doExtract(safeName, profileDir, archivePath, originalName);
  } finally {
    await fs.unlink(lockFile).catch(() => {});
  }
}

async function _doExtract(safeName, profileDir, archivePath, originalName) {

  const { execFile } = require('child_process');

  function execFileAsync(cmd, args, opts = {}) {
    return new Promise((resolve, reject) => {
      execFile(cmd, args, opts, (err, stdout, stderr) => {
        if (err) { err.stdout = stdout; err.stderr = stderr; reject(err); }
        else resolve({ stdout, stderr });
      });
    });
  }

  // Detect archive format from original filename
  const ext = (originalName || '').toLowerCase().replace(/^.*\./, '.');
  const use7z = ext === '.exe' || ext === '.7z';

  let entryCount = 0;
  let totalUncompressed = 0;

  if (use7z) {
    // ---- 7z path (for .exe / .7z) ----
    let listOutput;
    try {
      const result = await execFileAsync('7z', ['l', archivePath], { maxBuffer: 10 * 1024 * 1024 });
      listOutput = result.stdout;
    } catch (err) {
      throw Object.assign(new Error('Invalid archive: ' + (err.stderr || err.message)), { statusCode: 400 });
    }

    const lines = listOutput.split('\n');
    let inEntries = false;
    for (const line of lines) {
      if (line.startsWith('---')) {
        inEntries = !inEntries;
        continue;
      }
      if (!inEntries) continue;

      const m = line.match(/^\S+\s+\S+\s+\S+\s+(\d+)\s+\d+\s+(.+)$/);
      if (!m) continue;

      const size = parseInt(m[1], 10);
      const entryName = m[2].trim();
      if (!entryName) continue;
      entryCount++;

      if (entryName.includes('..')) {
        throw Object.assign(new Error(`Archive contains path traversal: ${entryName}`), { statusCode: 400 });
      }
      if (entryName.startsWith('/')) {
        throw Object.assign(new Error(`Archive contains absolute path: ${entryName}`), { statusCode: 400 });
      }

      totalUncompressed += size;
    }

    if (entryCount > MAX_ZIP_ENTRIES) {
      throw Object.assign(
        new Error(`Archive contains too many entries: ${entryCount} (max ${MAX_ZIP_ENTRIES})`),
        { statusCode: 400 }
      );
    }

    if (totalUncompressed > MAX_ZIP_SIZE) {
      throw Object.assign(
        new Error(`Archive uncompressed size too large: ${Math.round(totalUncompressed / 1024 / 1024)}MB (max ${Math.round(MAX_ZIP_SIZE / 1024 / 1024)}MB)`),
        { statusCode: 400 }
      );
    }

    // Extract to temp dir first, then validate paths and move (defense-in-depth)
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'linbo-extract-'));
    try {
      await execFileAsync('7z', ['x', `-o${tmpDir}`, '-aoa', archivePath], {
        maxBuffer: 10 * 1024 * 1024,
        timeout: 600000, // 10 min
      });
      // Validate: no extracted file escapes tmpDir, remove symlinks before move
      await validateExtractedPaths(tmpDir);
      await removeSymlinks(tmpDir);
      // Move contents to profileDir
      await moveContents(tmpDir, profileDir);
    } catch (err) {
      if (err.statusCode) throw err;
      throw Object.assign(
        new Error('Archive extraction failed: ' + (err.stderr || err.message)),
        { statusCode: 500 }
      );
    } finally {
      await fs.rm(tmpDir, { recursive: true, force: true }).catch(() => {});
    }

    // Inno Setup .exe detection
    if (ext === '.exe') {
      const extracted = await fs.readdir(profileDir);
      const peSections = ['.text', '.rdata', '.rsrc', '.data', '.idata', '.edata', '.bss', '.tls', '.itext', '.didata', 'CERTIFICATE'];
      const nonMetaFiles = extracted.filter(f => f !== 'match.conf');
      const allPE = nonMetaFiles.every(f => peSections.includes(f) || f === '[0]');
      if (allPE && nonMetaFiles.length > 0) {
        for (const f of nonMetaFiles) {
          await fs.rm(path.join(profileDir, f), { recursive: true, force: true });
        }
        try {
          await execFileAsync('innoextract', ['-e', '-d', profileDir, archivePath], {
            maxBuffer: 50 * 1024 * 1024,
            timeout: 600000,
          });
          const topEntries = await fs.readdir(profileDir);
          const nonMeta = topEntries.filter(f => f !== 'match.conf');
          if (nonMeta.length === 1) {
            const singleDir = path.join(profileDir, nonMeta[0]);
            try {
              const st = await fs.stat(singleDir);
              if (st.isDirectory()) {
                const innerFiles = await fs.readdir(singleDir);
                for (const f of innerFiles) {
                  await fs.rename(path.join(singleDir, f), path.join(profileDir, f));
                }
                await fs.rm(singleDir, { recursive: true, force: true });
              }
            } catch { /* not a directory */ }
          }
          entryCount = await countFiles(profileDir);
        } catch (innoErr) {
          throw Object.assign(
            new Error('Inno Setup extraction failed: ' + (innoErr.stderr || innoErr.message)),
            { statusCode: 500 }
          );
        }
      }
    }
  } else {
    // ---- unzip path (for .zip and fallback) ----
    let listOutput;
    try {
      const result = await execFileAsync('unzip', ['-l', archivePath], { maxBuffer: 10 * 1024 * 1024 });
      listOutput = result.stdout;
    } catch (err) {
      throw Object.assign(new Error('Invalid ZIP file: ' + (err.stderr || err.message)), { statusCode: 400 });
    }

    const lines = listOutput.split('\n');
    for (const line of lines) {
      const match = line.match(/^\s*(\d+)\s+\d{2}-\d{2}-\d{2,4}\s+\d{2}:\d{2}\s+(.+)$/);
      if (!match) continue;

      const size = parseInt(match[1], 10);
      const entryName = match[2];
      entryCount++;

      if (entryName.includes('..')) {
        throw Object.assign(new Error(`ZIP contains path traversal: ${entryName}`), { statusCode: 400 });
      }
      if (entryName.startsWith('/')) {
        throw Object.assign(new Error(`ZIP contains absolute path: ${entryName}`), { statusCode: 400 });
      }

      totalUncompressed += size;
    }

    if (entryCount > MAX_ZIP_ENTRIES) {
      throw Object.assign(
        new Error(`ZIP contains too many entries: ${entryCount} (max ${MAX_ZIP_ENTRIES})`),
        { statusCode: 400 }
      );
    }

    if (totalUncompressed > MAX_ZIP_SIZE) {
      throw Object.assign(
        new Error(`ZIP uncompressed size too large: ${Math.round(totalUncompressed / 1024 / 1024)}MB (max ${Math.round(MAX_ZIP_SIZE / 1024 / 1024)}MB)`),
        { statusCode: 400 }
      );
    }

    // Extract to temp dir first, then validate paths and move (defense-in-depth)
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'linbo-extract-'));
    try {
      await execFileAsync('unzip', ['-o', '-K', archivePath, '-d', tmpDir], {
        maxBuffer: 10 * 1024 * 1024,
        timeout: 600000, // 10 min
      });
      // Validate: no extracted file escapes tmpDir, remove symlinks before move
      await validateExtractedPaths(tmpDir);
      await removeSymlinks(tmpDir);
      // Move contents to profileDir
      await moveContents(tmpDir, profileDir);
    } catch (err) {
      if (err.statusCode) throw err;
      throw Object.assign(
        new Error('ZIP extraction failed: ' + (err.stderr || err.message)),
        { statusCode: 500 }
      );
    } finally {
      await fs.rm(tmpDir, { recursive: true, force: true }).catch(() => {});
    }
  }

  // Post-extraction: remove any symlinks
  await removeSymlinks(profileDir);

  ws.broadcast('drivers.archive_extracted', { folder: safeName, entryCount, totalUncompressed });

  return { entryCount, totalUncompressed };
}

module.exports = {
  createProfile,
  listProfiles,
  getMatchConf,
  parseMatchConf,
  updateMatchConf,
  listFiles,
  uploadFile,
  deleteFile,
  deleteProfile,
  extractArchive,
  readImageConf,
  listAvailableImages,
  setProfileImage,
  removeProfileImage,
  regeneratePostsync,
};
