#!/bin/sh
set -e

# =============================================================================
# LINBO Docker — ISC DHCP Server Container
#
# Full-featured DHCP server for the entire school network.
# Serves all devices: Windows PCs, Linux clients, printers, TVs, etc.
# Config matches the LMN server / caching-server reference implementation.
# =============================================================================

# ---- Environment variables (from docker-compose.yml) ----
LINBO_SERVER_IP="${LINBO_SERVER_IP:-10.0.0.1}"
DHCP_INTERFACE="${DHCP_INTERFACE:-eth0}"
LMN_SCHOOL="${LMN_SCHOOL:-default-school}"
LMN_SERVER_IP="${LMN_SERVER_IP:-${LINBO_SERVER_IP}}"
LINBO_DOMAIN="${LINBO_DOMAIN:-linuxmuster.lan}"
LINBO_DNS="${LINBO_DNS:-${LMN_SERVER_IP}}"
LINBO_GATEWAY="${LINBO_GATEWAY:-10.0.0.254}"
LINBO_HOSTNAME="${LINBO_HOSTNAME:-linbo-docker}"

echo "[DHCP] LINBO Docker ISC DHCP Server"
echo "[DHCP] Docker IP (next-server):  ${LINBO_SERVER_IP}"
echo "[DHCP] LMN Server IP:            ${LMN_SERVER_IP}"
echo "[DHCP] Domain:                    ${LINBO_DOMAIN}"
echo "[DHCP] DNS:                       ${LINBO_DNS}"
echo "[DHCP] Gateway:                   ${LINBO_GATEWAY}"
echo "[DHCP] Hostname:                  ${LINBO_HOSTNAME}"
echo "[DHCP] Interface:                 ${DHCP_INTERFACE}"
echo "[DHCP] School:                    ${LMN_SCHOOL}"

# ---- Generate /etc/dhcp/dhcpd.conf (LMN reference-compatible) ----
echo "[DHCP] Generating /etc/dhcp/dhcpd.conf ..."

cat > /etc/dhcp/dhcpd.conf <<EOF
# /etc/dhcp/dhcpd.conf
# Generated by LINBO Docker DHCP container
# Reference: linuxmuster.net 7.3 dhcpd.conf template + caching-server-satellite

# ---- Server identification ----
server-identifier ${LINBO_HOSTNAME};
update-static-leases true;
ddns-update-style none;

# ---- Network options (served to ALL clients: Windows, Linux, printers, etc.) ----
server-name "${LINBO_HOSTNAME}.${LINBO_DOMAIN}";
option domain-name "${LINBO_DOMAIN}";
option domain-name-servers ${LINBO_DNS};
option netbios-name-servers ${LMN_SERVER_IP};
option ntp-servers ${LINBO_GATEWAY};
option font-servers ${LMN_SERVER_IP};
use-host-decl-names on;

# ---- Lease times ----
default-lease-time 600;
max-lease-time 7200;

# ---- Server mode ----
authoritative;
log-facility local7;

# ---- Boot services ----
allow booting;
allow bootp;

# ---- GRUB menu option (used by LINBO GRUB for config selection) ----
option grubmenu code 150 = text;
option arch code 93 = unsigned integer 16; #RFC4578

# ---- Architecture-specific PXE boot filenames ----
if option arch = 00:06 {
  filename "boot/grub/i386-efi/core.efi";
} else if option arch = 00:07 {
  filename "boot/grub/x86_64-efi/core.efi";
} else {
  filename "boot/grub/i386-pc/core.0";
}

# ---- TFTP server (this Docker instance) ----
next-server ${LINBO_SERVER_IP};

# ---- Subnet definitions (synced from LMN server by sync service) ----
include "/etc/dhcp/subnets.conf";

group {

  # Longer lease time for registered devices (2 days)
  default-lease-time 172800;
  max-lease-time 172800;

  # Device reservations per school (synced from LMN server by sync service)
  include "/etc/dhcp/devices.conf";

  # Custom overrides (user-editable, not overwritten by sync)
  include "/etc/dhcp/custom.conf";

}
EOF

echo "[DHCP] dhcpd.conf written (full LMN-compatible config)"

# ---- Generate /etc/dhcp/devices.conf (includes school-specific file) ----
mkdir -p /etc/dhcp/devices
cat > /etc/dhcp/devices.conf <<EOF
# devices.conf — includes school-specific device reservations
include "/etc/dhcp/devices/${LMN_SCHOOL}.conf";
EOF

# ---- Generate /etc/dhcp/custom.conf (empty placeholder, not overwritten) ----
if [ ! -f /etc/dhcp/custom.conf ]; then
  cat > /etc/dhcp/custom.conf <<EOF
# custom.conf — place custom DHCP options here
# This file is preserved across container restarts and sync updates
EOF
  echo "[DHCP] Created custom.conf placeholder"
fi

# ---- Create placeholder files so dhcpd does not crash on first start ----
if [ ! -f /etc/dhcp/subnets.conf ]; then
  cat > /etc/dhcp/subnets.conf <<EOF
# subnets.conf — placeholder (will be populated by sync from LMN server)
# If sync is not configured, add your subnet definition here manually:
# subnet 10.0.0.0 netmask 255.255.0.0 {
#   option routers 10.0.0.254;
#   option subnet-mask 255.255.0.0;
#   option broadcast-address 10.0.255.255;
#   range 10.0.255.1 10.0.255.254;
# }
EOF
  echo "[DHCP] Created placeholder subnets.conf"
fi

if [ ! -f "/etc/dhcp/devices/${LMN_SCHOOL}.conf" ]; then
  echo "# ${LMN_SCHOOL}.conf — placeholder (will be populated by sync)" > "/etc/dhcp/devices/${LMN_SCHOOL}.conf"
  echo "[DHCP] Created placeholder devices/${LMN_SCHOOL}.conf"
fi

# ---- Wait for sync service to write real DHCP configs ----
# On first boot the API runs an initial sync that writes subnets.conf and
# devices/{school}.conf to the shared volume. We wait here until subnets.conf
# has actual subnet declarations (not just a placeholder comment).
SHARED_DIR="/srv/linbo/dhcp"
MAX_WAIT=120
WAITED=0

echo "[DHCP] Waiting for sync service to provide DHCP configs..."
while [ "$WAITED" -lt "$MAX_WAIT" ]; do
  # Check if subnets.conf exists AND contains a real subnet declaration
  if [ -f "${SHARED_DIR}/subnets.conf" ] && grep -q "^subnet " "${SHARED_DIR}/subnets.conf" 2>/dev/null; then
    echo "[DHCP] subnets.conf ready (waited ${WAITED}s)"
    break
  fi
  sleep 3
  WAITED=$((WAITED + 3))
  [ $((WAITED % 15)) -eq 0 ] && echo "[DHCP] Still waiting for configs... (${WAITED}s/${MAX_WAIT}s)"
done

if [ "$WAITED" -ge "$MAX_WAIT" ]; then
  echo "[DHCP] WARNING: Timed out waiting for DHCP configs after ${MAX_WAIT}s"
  echo "[DHCP] Starting with placeholder configs — trigger a sync and restart this container"
fi

# ---- Copy configs from shared volume ----
if [ -f "${SHARED_DIR}/subnets.conf" ]; then
  cp "${SHARED_DIR}/subnets.conf" /etc/dhcp/subnets.conf
  echo "[DHCP] Copied subnets.conf from shared volume"
fi

if [ -f "${SHARED_DIR}/devices/${LMN_SCHOOL}.conf" ]; then
  cp "${SHARED_DIR}/devices/${LMN_SCHOOL}.conf" "/etc/dhcp/devices/${LMN_SCHOOL}.conf"
  echo "[DHCP] Copied devices/${LMN_SCHOOL}.conf from shared volume"
fi

# ---- Configure ISC DHCP server interface ----
echo "INTERFACESv4=\"${DHCP_INTERFACE}\"" > /etc/default/isc-dhcp-server
echo "[DHCP] Set INTERFACESv4=${DHCP_INTERFACE}"

# ---- Create PID directory and lease file ----
mkdir -p /var/run/dhcp-server
touch /var/lib/dhcp/dhcpd.leases

# ---- Start inotify watcher for live config reloads from sync service ----
/watch-config.sh &
echo "[DHCP] Config watcher started (PID $!)"

# ---- Start dhcpd in foreground ----
echo "[DHCP] Starting ISC DHCP server..."
exec dhcpd -f -d -cf /etc/dhcp/dhcpd.conf -pf /var/run/dhcp-server/dhcpd.pid
