#!/bin/bash
# setup-dhcp.sh — DHCP scaffold provisioning
# Idempotent: re-run safely, sentinel at /var/lib/linbo-native/.dhcp-scaffold-done
# Called by Phase 3 Plan 03 activation or manually during DHCP setup
# Usage: sudo ./scripts/server/setup-dhcp.sh [--force]
set -euo pipefail

ENV_FILE="/etc/linbo-native/.env"
DHCP_DIR="/etc/dhcp"
DEFAULT_IFACE_FILE="/etc/default/isc-dhcp-server"
SUDOERS_FILE="/etc/sudoers.d/linbo-dhcp"
SENTINEL="/var/lib/linbo-native/.dhcp-scaffold-done"

log_info()  { echo "[setup-dhcp] INFO:  $*"; }
log_ok()    { echo "[setup-dhcp] OK:    $*"; }
log_error() { echo "[setup-dhcp] ERROR: $*" >&2; }
log_warn()  { echo "[setup-dhcp] WARN:  $*" >&2; }

# Root guard
[[ "$EUID" -ne 0 ]] && log_error "Must run as root" && exit 1

# Sentinel check (idempotency) — skip if --force not passed
FORCE=false
[[ "${1:-}" == "--force" ]] && FORCE=true
if [[ "$FORCE" == "false" && -f "$SENTINEL" ]]; then
    log_info "DHCP scaffold already done (sentinel: $SENTINEL). Use --force to re-run."
    exit 0
fi

log_info "Starting DHCP scaffold provisioning..."

# =============================================================================
# Step 1: Source .env
# =============================================================================
if [[ ! -f "$ENV_FILE" ]]; then
    log_error "$ENV_FILE not found — run setup.sh first"
    exit 1
fi
# Source only DHCP-relevant variables (avoid eval on untrusted input)
# Note: grep || true prevents set -e exit when variable is absent from .env
LINBO_SERVER_IP=$(grep '^LINBO_SERVER_IP=' "$ENV_FILE" | cut -d= -f2- | tr -d '"' | tr -d "'" || true)
LINBO_HOSTNAME=$(grep '^LINBO_HOSTNAME=' "$ENV_FILE" | cut -d= -f2- | tr -d '"' | tr -d "'" || true)
LMN_SERVER_IP=$(grep '^LMN_SERVER_IP=' "$ENV_FILE" | cut -d= -f2- | tr -d '"' | tr -d "'" || true)
LINBO_DOMAIN=$(grep '^LINBO_DOMAIN=' "$ENV_FILE" | cut -d= -f2- | tr -d '"' | tr -d "'" || true)
LINBO_GATEWAY=$(grep '^LINBO_GATEWAY=' "$ENV_FILE" | cut -d= -f2- | tr -d '"' | tr -d "'" || true)
LMN_SCHOOL=$(grep '^LMN_SCHOOL=' "$ENV_FILE" | cut -d= -f2- | tr -d '"' | tr -d "'" || true)
DHCP_INTERFACE=$(grep '^DHCP_INTERFACE=' "$ENV_FILE" | cut -d= -f2- | tr -d '"' | tr -d "'" || true)

# Apply defaults for optional vars
LINBO_HOSTNAME="${LINBO_HOSTNAME:-linbo-native}"
LMN_SERVER_IP="${LMN_SERVER_IP:-$LINBO_SERVER_IP}"
LINBO_DOMAIN="${LINBO_DOMAIN:-linuxmuster.lan}"
LINBO_GATEWAY="${LINBO_GATEWAY:-10.0.0.254}"
LMN_SCHOOL="${LMN_SCHOOL:-default-school}"

if [[ -z "$LINBO_SERVER_IP" ]]; then
    log_error "LINBO_SERVER_IP is not set in $ENV_FILE"
    exit 1
fi

log_info "LINBO_SERVER_IP=${LINBO_SERVER_IP}"
log_info "LINBO_HOSTNAME=${LINBO_HOSTNAME}"
log_info "LMN_SERVER_IP=${LMN_SERVER_IP}"
log_info "LINBO_DOMAIN=${LINBO_DOMAIN}"
log_info "LMN_SCHOOL=${LMN_SCHOOL}"

# =============================================================================
# Step 2: Auto-detect interface if DHCP_INTERFACE not set
# =============================================================================
if [[ -z "${DHCP_INTERFACE:-}" ]]; then
    DHCP_INTERFACE=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev") print $(i+1)}' | head -1)
    DHCP_INTERFACE="${DHCP_INTERFACE:-eth0}"
    log_info "DHCP_INTERFACE auto-detected: $DHCP_INTERFACE"
else
    log_info "DHCP_INTERFACE from .env: $DHCP_INTERFACE"
fi

# =============================================================================
# Step 3: Write /etc/default/isc-dhcp-server
# =============================================================================
echo "INTERFACESv4=\"${DHCP_INTERFACE}\"" > "$DEFAULT_IFACE_FILE"
log_ok "Written: $DEFAULT_IFACE_FILE (INTERFACESv4=${DHCP_INTERFACE})"

# =============================================================================
# Step 4: Create /etc/dhcp/devices/ directory
# =============================================================================
mkdir -p "${DHCP_DIR}/devices"
log_ok "Directory: ${DHCP_DIR}/devices"

# =============================================================================
# Step 5: Write static dhcpd.conf (the authoritative LINBO template)
# =============================================================================
# Based on live reference from 10.0.0.11/etc/dhcp/dhcpd.conf and
# containers/dhcp/entrypoint.sh — adapted for caching satellite.
# CRITICAL: Do NOT include events.conf (runs Samba DNS scripts absent on satellite)
cat > "${DHCP_DIR}/dhcpd.conf" << DHCPEOF
# /etc/dhcp/dhcpd.conf
# Generated by setup-dhcp.sh for LINBO Native Caching Satellite
# DO NOT EDIT — re-run setup-dhcp.sh --force to regenerate
# Dynamic subnet/device config comes from API sync (subnets.conf, devices/*.conf)

# ---- Server identification ----
server-identifier ${LINBO_HOSTNAME};
update-static-leases true;
ddns-update-style none;

# ---- Network options (served to all clients: Windows, Linux, printers, TVs) ----
server-name "${LINBO_HOSTNAME}.${LINBO_DOMAIN}";
option domain-name "${LINBO_DOMAIN}";
option domain-name-servers ${LMN_SERVER_IP};
option netbios-name-servers ${LMN_SERVER_IP};
option ntp-servers ${LINBO_GATEWAY};
option font-servers ${LMN_SERVER_IP};
use-host-decl-names on;

# ---- Lease times ----
default-lease-time 600;
max-lease-time 7200;

# ---- Server mode ----
authoritative;
log-facility local7;

# ---- Boot services ----
allow booting;
allow bootp;

# ---- GRUB menu option (LINBO-specific, option 150) ----
option grubmenu code 150 = text;
# Architecture detection (RFC 4578)
option arch code 93 = unsigned integer 16;

# ---- Architecture-specific PXE boot filenames ----
if option arch = 00:06 {
  filename "boot/grub/i386-efi/core.efi";
} else if option arch = 00:07 {
  filename "boot/grub/x86_64-efi/core.efi";
} else if option arch = 00:09 {
  filename "boot/grub/x86_64-efi/core.efi";
} else {
  filename "boot/grub/i386-pc/core.0";
}

# ---- TFTP server (this caching satellite) ----
next-server ${LINBO_SERVER_IP};

# ---- Subnet definitions (written by API sync from Authority /dhcp/export/isc-dhcp) ----
include "/etc/dhcp/subnets.conf";

group {
  # Longer lease time for registered devices (2 days)
  default-lease-time 172800;
  max-lease-time 172800;

  # Per-school host reservations (written by API sync per school)
  include "/etc/dhcp/devices.conf";

  # Custom overrides (user-editable, never overwritten by sync or setup)
  include "/etc/dhcp/custom.conf";
}
DHCPEOF
log_ok "Written: ${DHCP_DIR}/dhcpd.conf"

# =============================================================================
# Step 6: Write placeholder include files
# =============================================================================
# CRITICAL: missing files = dhcpd parse error

# subnets.conf — populated by API sync on first sync
if [[ ! -f "${DHCP_DIR}/subnets.conf" ]]; then
    cat > "${DHCP_DIR}/subnets.conf" << 'SUBEOF'
# subnets.conf — placeholder
# Populated automatically by linbo-api sync from the LMN Authority Server.
# Trigger a sync after setup to populate: POST /api/v1/sync/trigger
SUBEOF
    log_ok "Written: ${DHCP_DIR}/subnets.conf (placeholder)"
else
    log_info "Keeping existing ${DHCP_DIR}/subnets.conf"
fi

# devices/{school}.conf — populated by API sync
if [[ ! -f "${DHCP_DIR}/devices/${LMN_SCHOOL}.conf" ]]; then
    echo "# devices/${LMN_SCHOOL}.conf — placeholder (populated by API sync)" \
        > "${DHCP_DIR}/devices/${LMN_SCHOOL}.conf"
    log_ok "Written: ${DHCP_DIR}/devices/${LMN_SCHOOL}.conf (placeholder)"
else
    log_info "Keeping existing ${DHCP_DIR}/devices/${LMN_SCHOOL}.conf"
fi

# devices.conf — aggregator that includes all school-specific files
# Always regenerate from current devices/ contents
{
    echo "# devices.conf — includes per-school device reservations"
    echo "# Regenerated by setup-dhcp.sh — do not edit manually"
    for f in "${DHCP_DIR}/devices/"*.conf; do
        [[ -f "$f" ]] || continue
        echo "include \"$f\";"
    done
} > "${DHCP_DIR}/devices.conf"
log_ok "Written: ${DHCP_DIR}/devices.conf"

# custom.conf — user-editable, never overwritten
if [[ ! -f "${DHCP_DIR}/custom.conf" ]]; then
    cat > "${DHCP_DIR}/custom.conf" << 'CUSTEOF'
# custom.conf — place custom DHCP options here
# This file is preserved across setup-dhcp.sh runs and API sync updates.
CUSTEOF
    log_ok "Written: ${DHCP_DIR}/custom.conf (empty placeholder)"
else
    log_info "Keeping existing ${DHCP_DIR}/custom.conf (user-editable)"
fi

# =============================================================================
# Step 7: Set /etc/dhcp permissions so linbo user can write dynamic files
# =============================================================================
# /etc/dhcp/ stays owned by root but group-writable by linbo.
# The sudoers entry (Step 8) handles the actual restart.
# linbo user writes via API sync which runs as linbo (linbo-api.service).
chown root:root "${DHCP_DIR}"
chown -R root:root "${DHCP_DIR}/devices"
chgrp linbo "${DHCP_DIR}" "${DHCP_DIR}/devices"
chmod g+w "${DHCP_DIR}" "${DHCP_DIR}/devices"
log_ok "Permissions: ${DHCP_DIR} + ${DHCP_DIR}/devices (group linbo write)"

# =============================================================================
# Step 8: sudoers entry for linbo user (minimal privilege)
# =============================================================================
cat > "$SUDOERS_FILE" << 'SUDOEOF'
# /etc/sudoers.d/linbo-dhcp
# Allow linbo API service to restart isc-dhcp-server and validate config
linbo ALL=(root) NOPASSWD: /bin/systemctl restart isc-dhcp-server
linbo ALL=(root) NOPASSWD: /usr/sbin/dhcpd -t -cf /etc/dhcp/dhcpd.conf
SUDOEOF
chmod 440 "$SUDOERS_FILE"
log_ok "Written: $SUDOERS_FILE (chmod 440)"

# Validate sudoers entry
if ! visudo -c -f "$SUDOERS_FILE" &>/dev/null; then
    log_error "sudoers validation failed — removing $SUDOERS_FILE"
    rm -f "$SUDOERS_FILE"
    exit 1
fi
log_ok "sudoers entry validated"

# =============================================================================
# Step 9: Validate dhcpd.conf (config test)
# =============================================================================
log_info "Running dhcpd config test..."
if dhcpd -t -cf "${DHCP_DIR}/dhcpd.conf" 2>&1; then
    log_ok "dhcpd config test passed"
else
    log_warn "dhcpd config test failed — isc-dhcp-server may not start"
    log_warn "Check ${DHCP_DIR}/dhcpd.conf and include files"
fi

# =============================================================================
# Step 10: Write sentinel
# =============================================================================
mkdir -p "$(dirname "$SENTINEL")"
printf '%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$SENTINEL"
log_ok "Sentinel written: $SENTINEL"
log_ok "DHCP scaffold provisioning complete."
